# from: https://www.makeuseof.com/how-to-install-arch-linux-kvm-configure-virtual-machine/

- name: Test
  debug:
    msg: "Install from Guide!"

# Comment out Extra Repository: https://itsfoss.com/arch-linux-repos/
- name: Disable Extra Repository
  include_tasks: Archlinux/Repository/disable Extra Repository.yml

- name: Install ebtables - from Core Repository
  community.general.pacman:
    name:
      -  ebtables
    state: present
  become: true

- name: Enable Extra Repository
  include_tasks: Archlinux/Repository/enable Extra Repository.yml


- name: Install package
  community.general.pacman:
    name:
      - qemu-full
      - virt-manager
      - virt-viewer
      - dnsmasq
      - bridge-utils
      - libguestfs
      - vde2
      - openbsd-netcat
    state: present
  become: true

- name: Install Fix
  community.general.pacman:
    name:
      - dmidecode
    state: present
  become: true

- name: Replace unix_sock_group
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_group = "libvirt"'
    replace: 'unix_sock_group = "libvirt"'
  become: true

- name: Replace unix_sock_rw_perms 
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_rw_perms = "0770"'
    replace: 'unix_sock_rw_perms = "0770"'
  become: true

- name: add your user to the libvirt group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: libvirt
    append: yes
  become: true

- name: Enable libvirtd Service
  ansible.builtin.systemd_service:
    name: libvirtd.service
    state: started
    enabled: true
  become: true