---
# https://ubuntu.com/blog/kvm-hyphervisor
- name: Install KVM
  ansible.builtin.apt:
    pkg:
    - bridge-utils
    - libvirt-clients
    - libvirt-daemon
    - qemu-system
    - qemu-kvm
  become: true
