---
# handlers file for Libvirt
- name: Start and enable Libvirtd service
  ansible.builtin.systemd_service:
    name: libvirtd
    state: started
    enabled: true
  become: true

- name: Restart libvirtd.service
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: libvirtd
  become: true
