- name: start the libvirtd service
  ansible.builtin.systemd:
    name: libvirtd
    state: started
    enabled: true
  become: true

- name: Pacman update cache
  community.general.pacman:
    update_cache: true
  become: true