# from: https://www.makeuseof.com/how-to-install-arch-linux-kvm-configure-virtual-machine/

- name: Test
  debug:
    msg: "Install from Guide!"

- name: Update Cache
  community.general.pacman:
    # name: foo
    # state: latest
    update_cache: true
  become: true

- name: Install Qemu
  include_tasks: Archlinux/Qemu by architecture/main.yml

- name: use Ebtables
  include_tasks: Archlinux/Ebtables/main.yml
  when: arch_use_ebtables

- name: Install package
  community.general.pacman:
    name:
      # - qemu-full # Not available in Manjaro!
      - virt-manager
      - virt-viewer
      - dnsmasq
      - bridge-utils
      - libguestfs
      - vde2
      - openbsd-netcat
    state: present
  become: true

- name: Install Fix
  community.general.pacman:
    name:
      - dmidecode
    state: present
  become: true

- name: Replace unix_sock_group
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_group = "libvirt"'
    replace: 'unix_sock_group = "libvirt"'
  become: true

- name: Replace unix_sock_rw_perms 
  ansible.builtin.replace:
    path: /etc/libvirt/libvirtd.conf
    regexp: '^#unix_sock_rw_perms = "0770"'
    replace: 'unix_sock_rw_perms = "0770"'
  become: true

- name: add your user to the libvirt group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: libvirt
    append: yes
  become: true

- name: Enable libvirtd Service
  ansible.builtin.systemd_service:
    name: libvirtd.service
    state: started
    enabled: true
  become: true